
package com.app;

import java.awt.BorderLayout;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import static com.app.Dashboard.content;
import com.bd.Statements;

/**
 * 
 * @author diego
 */
public class UpCliente extends javax.swing.JPanel {

    private boolean edit;
    private String idus;
    private Statements statement;
    
    /**
     * Creates new form
     */
    public UpCliente() {
        initComponents();
        edit = false;
        statement = new Statements(Dashboard.user, Dashboard.pwd);
    }
    
    public UpCliente(String usid, String unombre, String uapellidos, String fecha_nacimiento, String fecha_inicio, String fecha_final, String utelefono, String uemail, String umunicipio, String uprovincia, String nombre_plan, String ubono) {
        statement = new Statements(Dashboard.user, Dashboard.pwd);
        initComponents();
        
        idus = usid;
        name.setText(unombre);
        apellidos.setText(uapellidos);
        fechaNacimiento.setText(fecha_nacimiento);
        fechaInicio.setText(fecha_inicio);
        fechaFinal.setText(fecha_final);
        telefono.setText(utelefono);
        email.setText(uemail);
        municipio.setText(umunicipio);
        provincia.setText(uprovincia);
        plan.setText(nombre_plan);
        bono.setText(ubono);
        
        edit = true;
        jLabel1.setText("Guardar");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        body = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        Text1 = new javax.swing.JLabel();
        Text2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        email = new javax.swing.JTextField();
        telefono = new javax.swing.JTextField();
        button = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Text3 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        Text4 = new javax.swing.JLabel();
        apellidos = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        Text5 = new javax.swing.JLabel();
        fechaNacimiento = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        Text6 = new javax.swing.JLabel();
        fechaInicio = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        Text7 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        municipio = new javax.swing.JTextField();
        Text8 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        provincia = new javax.swing.JTextField();
        Text9 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        plan = new javax.swing.JTextField();
        Text10 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        bono = new javax.swing.JTextField();
        Text11 = new javax.swing.JLabel();
        fechaFinal = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(750, 430));
        setPreferredSize(new java.awt.Dimension(750, 430));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(body, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Title.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Title.setText("Registrar nuevo paciente");
        add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        Text1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text1.setText("Email *");
        add(Text1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, -1, -1));

        Text2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text2.setText("Teléfono *");
        add(Text2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator1.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 260, 10));

        jSeparator2.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator2.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 260, 10));

        jSeparator3.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 10, 350));

        email.setForeground(new java.awt.Color(102, 102, 102));
        email.setText("Ingrese un email");
        email.setBorder(null);
        email.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                emailMousePressed(evt);
            }
        });
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 260, 30));

        telefono.setForeground(new java.awt.Color(102, 102, 102));
        telefono.setText("Ingrese el teléfono");
        telefono.setBorder(null);
        telefono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                telefonoMousePressed(evt);
            }
        });
        telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonoActionPerformed(evt);
            }
        });
        add(telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 260, 30));

        button.setBackground(new java.awt.Color(18, 90, 173));
        button.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonMousePressed(evt);
            }
        });
        button.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registrar");
        button.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        add(button, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 380, 160, 40));

        Text3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text3.setText("Nombre *");
        add(Text3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        name.setForeground(new java.awt.Color(102, 102, 102));
        name.setText("Ingrese el nombre");
        name.setBorder(null);
        name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nameMousePressed(evt);
            }
        });
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 260, 30));

        jSeparator4.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator4.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 260, 10));

        Text4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text4.setText("Apellidos *");
        add(Text4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        apellidos.setForeground(new java.awt.Color(102, 102, 102));
        apellidos.setText("Ingrese los apellidos");
        apellidos.setBorder(null);
        apellidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                apellidosMousePressed(evt);
            }
        });
        apellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellidosActionPerformed(evt);
            }
        });
        add(apellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 260, 30));

        jSeparator5.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator5.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 260, 10));

        Text5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text5.setText("Fecha de nacimiento *");
        add(Text5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        fechaNacimiento.setForeground(new java.awt.Color(102, 102, 102));
        fechaNacimiento.setText("Ingrese la fecha de nacimiento");
        fechaNacimiento.setBorder(null);
        fechaNacimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                fechaNacimientoMousePressed(evt);
            }
        });
        fechaNacimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaNacimientoActionPerformed(evt);
            }
        });
        add(fechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 260, 30));

        jSeparator6.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator6.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 260, 10));

        Text6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text6.setText("Fecha de inicio *");
        add(Text6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        fechaInicio.setForeground(new java.awt.Color(102, 102, 102));
        fechaInicio.setText("Ingrese la fecha de inicio");
        fechaInicio.setBorder(null);
        fechaInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                fechaInicioMousePressed(evt);
            }
        });
        fechaInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaInicioActionPerformed(evt);
            }
        });
        add(fechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 260, 30));

        jSeparator7.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator7.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 260, 10));

        Text7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text7.setText("Municipio *");
        add(Text7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, -1, -1));

        jSeparator8.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator8.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 260, 10));

        municipio.setForeground(new java.awt.Color(102, 102, 102));
        municipio.setText("Ingrese el municipio");
        municipio.setBorder(null);
        municipio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                municipioMousePressed(evt);
            }
        });
        municipio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                municipioActionPerformed(evt);
            }
        });
        add(municipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 260, 30));

        Text8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text8.setText("Provincia *");
        add(Text8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, -1, -1));

        jSeparator9.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator9.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 260, 10));

        provincia.setForeground(new java.awt.Color(102, 102, 102));
        provincia.setText("Ingrese una provincia");
        provincia.setBorder(null);
        provincia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                provinciaMousePressed(evt);
            }
        });
        provincia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                provinciaActionPerformed(evt);
            }
        });
        add(provincia, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 260, 30));

        Text9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text9.setText("Plan *");
        add(Text9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, -1, -1));

        jSeparator10.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator10.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, 260, 10));

        plan.setForeground(new java.awt.Color(102, 102, 102));
        plan.setText("Ingrese un plan");
        plan.setBorder(null);
        plan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                planMousePressed(evt);
            }
        });
        plan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                planActionPerformed(evt);
            }
        });
        add(plan, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, 260, 30));

        Text10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text10.setText("Bono *");
        add(Text10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, -1, -1));

        jSeparator11.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator11.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 360, 260, 10));

        bono.setForeground(new java.awt.Color(102, 102, 102));
        bono.setText("Ingrese las sesiones");
        bono.setBorder(null);
        bono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bonoMousePressed(evt);
            }
        });
        bono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bonoActionPerformed(evt);
            }
        });
        add(bono, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, 260, 30));

        Text11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text11.setText("Fecha de finalización *");
        add(Text11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        fechaFinal.setForeground(new java.awt.Color(102, 102, 102));
        fechaFinal.setText("Ingrese la fecha de finalización");
        fechaFinal.setToolTipText("");
        fechaFinal.setBorder(null);
        fechaFinal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                fechaFinalMousePressed(evt);
            }
        });
        fechaFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaFinalActionPerformed(evt);
            }
        });
        add(fechaFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 260, 30));

        jSeparator12.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator12.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 260, 10));
    }// </editor-fold>//GEN-END:initComponents

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void telefonoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_telefonoMousePressed
       
       if(name.getText().equals("") || name.getText() == null || name.getText().equals(" "))
            name.setText("Ingrese el nombre");
       if(apellidos.getText().equals("") || apellidos.getText() == null || apellidos.getText().equals(" "))
            apellidos.setText("Ingrese los apellidos");
       if(fechaNacimiento.getText().equals("") || fechaNacimiento.getText() == null || fechaNacimiento.getText().equals(" "))
            fechaNacimiento.setText("Ingrese la fecha de nacimiento");
       if(fechaInicio.getText().equals("") || fechaInicio.getText() == null || fechaInicio.getText().equals(" "))
           fechaInicio.setText("Ingrese la fecha de inicio");
       if(telefono.getText().equals("Ingrese el teléfono"))
            telefono.setText("");
       if(email.getText().equals("") || email.getText() == null || email.getText().equals(" "))
            email.setText("Ingrese un email");
       if(municipio.getText().equals("") || municipio.getText() == null || municipio.getText().equals(" "))
            municipio.setText("Ingrese el municipio");
       if(provincia.getText().equals("") || provincia.getText() == null || provincia.getText().equals(" "))
            provincia.setText("Ingrese una provincia");
       if(plan.getText().equals("") || plan.getText() == null || plan.getText().equals(" "))
            plan.setText("Ingrese un plan");
       if(fechaFinal.getText().equals("") || fechaFinal.getText() == null || fechaFinal.getText().equals(" "))
           fechaFinal.setText("Ingrese la fecha de finalización");
        if(bono.getText().equals("") || bono.getText() == null || bono.getText().equals(" "))
           bono.setText("Ingrese las sesiones");
    }//GEN-LAST:event_telefonoMousePressed

    private void emailMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailMousePressed
        if(name.getText().equals("") || name.getText() == null || name.getText().equals(" "))
            name.setText("Ingrese el nombre");
       if(apellidos.getText().equals("") || apellidos.getText() == null || apellidos.getText().equals(" "))
            apellidos.setText("Ingrese los apellidos");
       if(fechaNacimiento.getText().equals("") || fechaNacimiento.getText() == null || fechaNacimiento.getText().equals(" "))
            fechaNacimiento.setText("Ingrese la fecha de nacimiento");
       if(fechaInicio.getText().equals("") || fechaInicio.getText() == null || fechaInicio.getText().equals(" "))
           fechaInicio.setText("Ingrese la fecha de inicio");
       if(telefono.getText().equals("") || telefono.getText() == null || telefono.getText().equals(" "))
            telefono.setText("Ingrese el teléfono");
       if(email.getText().equals("Ingrese un email"))
            email.setText("");
       if(municipio.getText().equals("") || municipio.getText() == null || municipio.getText().equals(" "))
            municipio.setText("Ingrese el municipio");
       if(provincia.getText().equals("") || provincia.getText() == null || provincia.getText().equals(" "))
            provincia.setText("Ingrese una provincia");
       if(plan.getText().equals("") || plan.getText() == null || plan.getText().equals(" "))
            plan.setText("Ingrese un plan");
       if(fechaFinal.getText().equals("") || fechaFinal.getText() == null || fechaFinal.getText().equals(" "))
           fechaFinal.setText("Ingrese la fecha de finalización");
        if(bono.getText().equals("") || bono.getText() == null || bono.getText().equals(" "))
           bono.setText("Ingrese las sesiones");
    }//GEN-LAST:event_emailMousePressed

    private void buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMouseEntered
        setColor(button);
    }//GEN-LAST:event_buttonMouseEntered

    private void buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMouseExited
        resetColor(button);
    }//GEN-LAST:event_buttonMouseExited

    private void nameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameMousePressed
       if(name.getText().equals("Ingrese el nombre"))
            name.setText("");
       if(apellidos.getText().equals("") || apellidos.getText() == null || apellidos.getText().equals(" "))
            apellidos.setText("Ingrese los apellidos");
       if(fechaNacimiento.getText().equals("") || fechaNacimiento.getText() == null || fechaNacimiento.getText().equals(" "))
            fechaNacimiento.setText("Ingrese la fecha de nacimiento");
       if(fechaInicio.getText().equals("") || fechaInicio.getText() == null || fechaInicio.getText().equals(" "))
           fechaInicio.setText("Ingrese la fecha de inicio");
       if(telefono.getText().equals("") || telefono.getText() == null || telefono.getText().equals(" "))
            telefono.setText("Ingrese el teléfono");
       if(email.getText().equals("") || email.getText() == null || email.getText().equals(" "))
            email.setText("Ingrese un email");
       if(municipio.getText().equals("") || municipio.getText() == null || municipio.getText().equals(" "))
            municipio.setText("Ingrese el municipio");
       if(provincia.getText().equals("") || provincia.getText() == null || provincia.getText().equals(" "))
            provincia.setText("Ingrese una provincia");
       if(plan.getText().equals("") || plan.getText() == null || plan.getText().equals(" "))
            plan.setText("Ingrese un plan");
       if(fechaFinal.getText().equals("") || fechaFinal.getText() == null || fechaFinal.getText().equals(" "))
           fechaFinal.setText("Ingrese la fecha de finalización");
        if(bono.getText().equals("") || bono.getText() == null || bono.getText().equals(" "))
           bono.setText("Ingrese las sesiones");
       
    }//GEN-LAST:event_nameMousePressed

    private void apellidosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_apellidosMousePressed
       if(name.getText().equals("") || name.getText() == null || name.getText().equals(" "))
            name.setText("Ingrese el nombre");
       if(apellidos.getText().equals("Ingrese los apellidos"))
            apellidos.setText("");
       if(fechaNacimiento.getText().equals("") || fechaNacimiento.getText() == null || fechaNacimiento.getText().equals(" "))
            fechaNacimiento.setText("Ingrese la fecha de nacimiento");
       if(fechaInicio.getText().equals("") || fechaInicio.getText() == null || fechaInicio.getText().equals(" "))
           fechaInicio.setText("Ingrese la fecha de inicio");
       if(telefono.getText().equals("") || telefono.getText() == null || telefono.getText().equals(" "))
            telefono.setText("Ingrese el teléfono");
       if(email.getText().equals("") || email.getText() == null || email.getText().equals(" "))
            email.setText("Ingrese un email");
       if(municipio.getText().equals("") || municipio.getText() == null || municipio.getText().equals(" "))
            municipio.setText("Ingrese el municipio");
       if(provincia.getText().equals("") || provincia.getText() == null || provincia.getText().equals(" "))
            provincia.setText("Ingrese una provincia");
       if(plan.getText().equals("") || plan.getText() == null || plan.getText().equals(" "))
            plan.setText("Ingrese un plan");
       if(fechaFinal.getText().equals("") || fechaFinal.getText() == null || fechaFinal.getText().equals(" "))
           fechaFinal.setText("Ingrese la fecha de finalización");
        if(bono.getText().equals("") || bono.getText() == null || bono.getText().equals(" "))
           bono.setText("Ingrese las sesiones");
    }//GEN-LAST:event_apellidosMousePressed

    private void apellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellidosActionPerformed

    private void fechaNacimientoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fechaNacimientoMousePressed
       if(name.getText().equals("") || name.getText() == null || name.getText().equals(" "))
            name.setText("Ingrese el nombre");
       if(apellidos.getText().equals("") || apellidos.getText() == null || apellidos.getText().equals(" "))
            apellidos.setText("Ingrese los apellidos");
       if(fechaNacimiento.getText().equals("Ingrese la fecha de nacimiento"))
            fechaNacimiento.setText("");
       if(fechaInicio.getText().equals("") || fechaInicio.getText() == null || fechaInicio.getText().equals(" "))
           fechaInicio.setText("Ingrese la fecha de inicio");
       if(telefono.getText().equals("") || telefono.getText() == null || telefono.getText().equals(" "))
            telefono.setText("Ingrese el teléfono");
       if(email.getText().equals("") || email.getText() == null || email.getText().equals(" "))
            email.setText("Ingrese un email");
       if(municipio.getText().equals("") || municipio.getText() == null || municipio.getText().equals(" "))
            municipio.setText("Ingrese el municipio");
       if(provincia.getText().equals("") || provincia.getText() == null || provincia.getText().equals(" "))
            provincia.setText("Ingrese una provincia");
       if(plan.getText().equals("") || plan.getText() == null || plan.getText().equals(" "))
            plan.setText("Ingrese un plan");
       if(fechaFinal.getText().equals("") || fechaFinal.getText() == null || fechaFinal.getText().equals(" "))
           fechaFinal.setText("Ingrese la fecha de finalización");
        if(bono.getText().equals("") || bono.getText() == null || bono.getText().equals(" "))
           bono.setText("Ingrese las sesiones");
    }//GEN-LAST:event_fechaNacimientoMousePressed

    private void fechaNacimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaNacimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaNacimientoActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void telefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonoActionPerformed
    
    /**
     * Registra un nuevo cliente o edita los datos de un cliente ya registrado
     * @param evt 
     */
    private void buttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMousePressed
        if(name.getText().equals("Ingrese el nombre") || apellidos.getText().equals("Ingrese los apellidos")
            || fechaNacimiento.getText().equals("Ingrese la fecha de nacimiento") || fechaInicio.getText().equals("Ingrese la fecha de inicio") || telefono.getText().equals("Ingrese el teléfono")
            || email.getText().equals("Ingrese un email") || municipio.getText().equals("Ingrese el municipio") || provincia.getText().equals("Ingrese una provincia")){
            javax.swing.JOptionPane.showMessageDialog(this, "Faltan campos por rellenar \n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            name.requestFocus();
        }
        else
        {
            String ufechaFinal;
            String ubono;
            String uplan;
            
            if(fechaFinal.getText().equals("Ingrese la fecha de finalización") || fechaFinal.getText().equals("") || fechaFinal.getText() == null){
                ufechaFinal = null;
            }else{ufechaFinal = fechaFinal.getText();}
            
            if(bono.getText().equals("Ingrese las sesiones") || bono.getText().equals("") || bono.getText() == null){
                ubono = null;
            }else{ubono = bono.getText();}
            
            if(plan.getText().equals("Ingrese un plan") || plan.getText().equals("") || plan.getText() == null){
                uplan = null;
            }else{uplan = plan.getText();}
            
            String uname = name.getText();
            String uapellido = apellidos.getText();
            String ufechaNacimiento = fechaNacimiento.getText();
            String ufechaInicio = fechaInicio.getText();
            String utelefono = telefono.getText();
            String uemail = email.getText();
            String umunicipio = municipio.getText();
            String uprovincia = provincia.getText();
            

            if(uname == null || "".equals(uname) || uapellido == null || "".equals(uapellido) || ufechaNacimiento == null || "".equals(ufechaNacimiento) || ufechaInicio == null || "".equals(ufechaInicio) || utelefono == null || "".equals(utelefono) || uemail == null || "".equals(uemail) || uprovincia == null || "".equals(uprovincia) || umunicipio == null || "".equals(umunicipio)){
                javax.swing.JOptionPane.showMessageDialog(this, "Faltan campos por rellenar \n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                name.requestFocus();
            }
            else{ 
                if(edit)
                    if(ubono == null && uplan == null){
                        editUser(Integer.parseInt(idus), uname, uapellido, ufechaNacimiento, ufechaInicio, ufechaFinal, Integer.parseInt(utelefono), uemail, umunicipio, uprovincia, null, -1);
                    }else if(ubono == null && uplan != null){
                        editUser(Integer.parseInt(idus), uname, uapellido, ufechaNacimiento, ufechaInicio, ufechaFinal, Integer.parseInt(utelefono), uemail, umunicipio, uprovincia, uplan, -1);
                    }else if(ubono != null && uplan == null){
                        editUser(Integer.parseInt(idus), uname, uapellido, ufechaNacimiento, ufechaInicio, ufechaFinal, Integer.parseInt(utelefono), uemail, umunicipio, uprovincia, null, Integer.parseInt(ubono));
                    }else{editUser(Integer.parseInt(idus), uname, uapellido, ufechaNacimiento, ufechaInicio, ufechaFinal, Integer.parseInt(utelefono), uemail, umunicipio, uprovincia, uplan, Integer.parseInt(ubono));}

                else
                    if(ubono == null){
                        insertUser(uname, uapellido, ufechaNacimiento, ufechaInicio, Integer.parseInt(utelefono), uemail, umunicipio, uprovincia, uplan, -1);
                    }else{
                        insertUser(uname, uapellido, ufechaNacimiento, ufechaInicio, Integer.parseInt(utelefono), uemail, umunicipio, uprovincia, uplan, Integer.parseInt(ubono));
                    }



                name.setText("");
                apellidos.setText("");
                fechaNacimiento.setText("");
                fechaInicio.setText("");
                fechaFinal.setText("");
                telefono.setText("");
                email.setText("");
                municipio.setText("");
                provincia.setText("");
                plan.setText("");
                bono.setText("");

                if(edit){
                    Clientes p1 = new Clientes();
                    p1.setSize(750, 430);
                    p1.setLocation(0, 0);

                    content.removeAll();
                    content.add(p1, BorderLayout.CENTER);
                    content.revalidate();
                    content.repaint();
                }
            }
        }
    }//GEN-LAST:event_buttonMousePressed

    private void fechaInicioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fechaInicioMousePressed
       if(name.getText().equals("") || name.getText() == null || name.getText().equals(" "))
            name.setText("Ingrese el nombre");
       if(apellidos.getText().equals("") || apellidos.getText() == null || apellidos.getText().equals(" "))
            apellidos.setText("Ingrese los apellidos");
       if(fechaNacimiento.getText().equals("") || fechaNacimiento.getText() == null || fechaNacimiento.getText().equals(" "))
            fechaNacimiento.setText("Ingrese la fecha de nacimiento");
       if(fechaInicio.getText().equals("Ingrese la fecha de inicio"))
           fechaInicio.setText("");
       if(telefono.getText().equals("") || telefono.getText() == null || telefono.getText().equals(" "))
            telefono.setText("Ingrese el teléfono");
       if(email.getText().equals("") || email.getText() == null || email.getText().equals(" "))
            email.setText("Ingrese un email");
       if(municipio.getText().equals("") || municipio.getText() == null || municipio.getText().equals(" "))
            municipio.setText("Ingrese el municipio");
       if(provincia.getText().equals("") || provincia.getText() == null || provincia.getText().equals(" "))
            provincia.setText("Ingrese una provincia");
       if(plan.getText().equals("") || plan.getText() == null || plan.getText().equals(" "))
            plan.setText("Ingrese un plan");
       if(fechaFinal.getText().equals("") || fechaFinal.getText() == null || fechaFinal.getText().equals(" "))
           fechaFinal.setText("Ingrese la fecha de finalización");
        if(bono.getText().equals("") || bono.getText() == null || bono.getText().equals(" "))
           bono.setText("Ingrese las sesiones");
    }//GEN-LAST:event_fechaInicioMousePressed

    private void fechaInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaInicioActionPerformed

    private void municipioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_municipioMousePressed
        if(name.getText().equals("") || name.getText() == null || name.getText().equals(" "))
            name.setText("Ingrese el nombre");
       if(apellidos.getText().equals("") || apellidos.getText() == null || apellidos.getText().equals(" "))
            apellidos.setText("Ingrese los apellidos");
       if(fechaNacimiento.getText().equals("") || fechaNacimiento.getText() == null || fechaNacimiento.getText().equals(" "))
            fechaNacimiento.setText("Ingrese la fecha de nacimiento");
       if(fechaInicio.getText().equals("") || fechaInicio.getText() == null || fechaInicio.getText().equals(" "))
           fechaInicio.setText("Ingrese la fecha de inicio");
       if(telefono.getText().equals("") || telefono.getText() == null || telefono.getText().equals(" "))
            telefono.setText("Ingrese el teléfono");
       if(email.getText().equals("") || email.getText() == null || email.getText().equals(" "))
            email.setText("Ingrese un email");
       if(municipio.getText().equals("Ingrese el municipio"))
            municipio.setText("");
       if(provincia.getText().equals("") || provincia.getText() == null || provincia.getText().equals(" "))
            provincia.setText("Ingrese una provincia");
       if(plan.getText().equals("") || plan.getText() == null || plan.getText().equals(" "))
            plan.setText("Ingrese un plan");
       if(fechaFinal.getText().equals("") || fechaFinal.getText() == null || fechaFinal.getText().equals(" "))
           fechaFinal.setText("Ingrese la fecha de finalización");
        if(bono.getText().equals("") || bono.getText() == null || bono.getText().equals(" "))
           bono.setText("Ingrese las sesiones");
    }//GEN-LAST:event_municipioMousePressed

    private void municipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_municipioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_municipioActionPerformed

    private void provinciaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_provinciaMousePressed
       if(name.getText().equals("") || name.getText() == null || name.getText().equals(" "))
            name.setText("Ingrese el nombre");
       if(apellidos.getText().equals("") || apellidos.getText() == null || apellidos.getText().equals(" "))
            apellidos.setText("Ingrese los apellidos");
       if(fechaNacimiento.getText().equals("") || fechaNacimiento.getText() == null || fechaNacimiento.getText().equals(" "))
            fechaNacimiento.setText("Ingrese la fecha de nacimiento");
       if(fechaInicio.getText().equals("") || fechaInicio.getText() == null || fechaInicio.getText().equals(" "))
           fechaInicio.setText("Ingrese la fecha de inicio");
       if(telefono.getText().equals("") || telefono.getText() == null || telefono.getText().equals(" "))
            telefono.setText("Ingrese el teléfono");
       if(email.getText().equals("") || email.getText() == null || email.getText().equals(" "))
            email.setText("Ingrese un email");
       if(municipio.getText().equals("") || municipio.getText() == null || municipio.getText().equals(" "))
            municipio.setText("Ingrese el municipio");
       if(provincia.getText().equals("Ingrese una provincia"))
            provincia.setText("");
       if(plan.getText().equals("") || plan.getText() == null || plan.getText().equals(" "))
            plan.setText("Ingrese un plan");
       if(fechaFinal.getText().equals("") || fechaFinal.getText() == null || fechaFinal.getText().equals(" "))
           fechaFinal.setText("Ingrese la fecha de finalización");
        if(bono.getText().equals("") || bono.getText() == null || bono.getText().equals(" "))
           bono.setText("Ingrese las sesiones");
    }//GEN-LAST:event_provinciaMousePressed

    private void provinciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_provinciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_provinciaActionPerformed

    private void planMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_planMousePressed
        if(name.getText().equals("") || name.getText() == null || name.getText().equals(" "))
            name.setText("Ingrese el nombre");
       if(apellidos.getText().equals("") || apellidos.getText() == null || apellidos.getText().equals(" "))
            apellidos.setText("Ingrese los apellidos");
       if(fechaNacimiento.getText().equals("") || fechaNacimiento.getText() == null || fechaNacimiento.getText().equals(" "))
            fechaNacimiento.setText("Ingrese la fecha de nacimiento");
       if(fechaInicio.getText().equals("") || fechaInicio.getText() == null || fechaInicio.getText().equals(" "))
           fechaInicio.setText("Ingrese la fecha de inicio");
       if(telefono.getText().equals("") || telefono.getText() == null || telefono.getText().equals(" "))
            telefono.setText("Ingrese el teléfono");
       if(email.getText().equals("") || email.getText() == null || email.getText().equals(" "))
            email.setText("Ingrese un email");
       if(municipio.getText().equals("") || municipio.getText() == null || municipio.getText().equals(" "))
            municipio.setText("Ingrese el municipio");
        if(provincia.getText().equals("") || provincia.getText() == null || provincia.getText().equals(" "))
            provincia.setText("Ingrese una provincia");
       if(plan.getText().equals("Ingrese un plan"))
            plan.setText("");
       if(fechaFinal.getText().equals("") || fechaFinal.getText() == null || fechaFinal.getText().equals(" "))
           fechaFinal.setText("Ingrese la fecha de finalización");
        if(bono.getText().equals("") || bono.getText() == null || bono.getText().equals(" "))
           bono.setText("Ingrese las sesiones");
    }//GEN-LAST:event_planMousePressed

    private void planActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_planActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_planActionPerformed

    private void bonoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bonoMousePressed
       if(name.getText().equals("") || name.getText() == null || name.getText().equals(" "))
            name.setText("Ingrese el nombre");
       if(apellidos.getText().equals("") || apellidos.getText() == null || apellidos.getText().equals(" "))
            apellidos.setText("Ingrese los apellidos");
       if(fechaNacimiento.getText().equals("") || fechaNacimiento.getText() == null || fechaNacimiento.getText().equals(" "))
            fechaNacimiento.setText("Ingrese la fecha de nacimiento");
       if(fechaInicio.getText().equals("") || fechaInicio.getText() == null || fechaInicio.getText().equals(" "))
           fechaInicio.setText("Ingrese la fecha de inicio");
       if(telefono.getText().equals("") || telefono.getText() == null || telefono.getText().equals(" "))
            telefono.setText("Ingrese el teléfono");
       if(email.getText().equals("") || email.getText() == null || email.getText().equals(" "))
            email.setText("Ingrese un email");
       if(municipio.getText().equals("") || municipio.getText() == null || municipio.getText().equals(" "))
            municipio.setText("Ingrese el municipio");
        if(provincia.getText().equals("") || provincia.getText() == null || provincia.getText().equals(" "))
            provincia.setText("Ingrese una provincia");
       if(plan.getText().equals("") || plan.getText() == null || plan.getText().equals(" "))
            plan.setText("Ingrese un plan");
       if(fechaFinal.getText().equals("") || fechaFinal.getText() == null || fechaFinal.getText().equals(" "))
           fechaFinal.setText("Ingrese la fecha de finalización");
       if(bono.getText().equals("Ingrese las sesiones"))
           bono.setText("");
    }//GEN-LAST:event_bonoMousePressed

    private void bonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bonoActionPerformed

    private void fechaFinalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fechaFinalMousePressed
        if(name.getText().equals("") || name.getText() == null || name.getText().equals(" "))
            name.setText("Ingrese el nombre");
       if(apellidos.getText().equals("") || apellidos.getText() == null || apellidos.getText().equals(" "))
            apellidos.setText("Ingrese los apellidos");
       if(fechaNacimiento.getText().equals("") || fechaNacimiento.getText() == null || fechaNacimiento.getText().equals(" "))
            fechaNacimiento.setText("Ingrese la fecha de nacimiento");
       if(fechaInicio.getText().equals("") || fechaInicio.getText() == null || fechaInicio.getText().equals(" "))
           fechaInicio.setText("Ingrese la fecha de inicio");
       if(telefono.getText().equals("") || telefono.getText() == null || telefono.getText().equals(" "))
            telefono.setText("Ingrese el teléfono");
       if(email.getText().equals("") || email.getText() == null || email.getText().equals(" "))
            email.setText("Ingrese un email");
       if(municipio.getText().equals("") || municipio.getText() == null || municipio.getText().equals(" "))
            municipio.setText("Ingrese el municipio");
        if(provincia.getText().equals("") || provincia.getText() == null || provincia.getText().equals(" "))
            provincia.setText("Ingrese una provincia");
       if(plan.getText().equals("") || plan.getText() == null || plan.getText().equals(" "))
            plan.setText("Ingrese un plan");
       if(fechaFinal.getText().equals("Ingrese la fecha de finalización"))
           fechaFinal.setText("");
       if(bono.getText().equals("") || bono.getText() == null || bono.getText().equals(" "))
           bono.setText("Ingrese las sesiones");
    }//GEN-LAST:event_fechaFinalMousePressed

    private void fechaFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaFinalActionPerformed

    private void setColor(JPanel panel){
        panel.setBackground(new Color(21,101,192));
    }
    
    private void resetColor(JPanel panel){
        panel.setBackground(new Color(18,90,173));
    }
    
    /**
     * Registra un nuevo cliente en la base de datos
     * @param nombre
     * @param apellidos
     * @param fecha_nacimiento
     * @param fecha_inicio
     * @param telefono
     * @param email
     * @param municipio
     * @param provincia
     * @param nombre_plan
     * @param bono
     * @throws SQLException 
     */
    public void insertUser(String nombre, String apellidos, String fecha_nacimiento, String fecha_inicio, int telefono, String email, String municipio, String provincia, String nombre_plan, int bono) {
        try{
            statement.insertCliente(nombre, apellidos, fecha_nacimiento, fecha_inicio, null, telefono, email, municipio, provincia, nombre_plan, bono);
            javax.swing.JOptionPane.showMessageDialog(this, "Cliente registrado correctamente \n", "HECHO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
        catch(SQLException e){
            javax.swing.JOptionPane.showMessageDialog(this, "No se ha podido añadir el cliente \n", "ERROR", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
        
        
    }
    
    /**
     * Edita los atributos asociados a un cliente ya creado en la base de datos
     * @param ID
     * @param nombre
     * @param apellidos
     * @param fecha_nacimiento
     * @param fecha_inicio
     * @param fecha_final
     * @param telefono
     * @param email
     * @param municipio
     * @param provincia
     * @param nombre_plan
     * @param bono
     * @throws SQLException 
     */
    public void editUser(int ID, String nombre, String apellidos, String fecha_nacimiento, String fecha_inicio, String fecha_final, int telefono, String email, String municipio, String provincia, String nombre_plan, int bono) {
       try{
            statement.updateCliente(ID, nombre, apellidos, fecha_nacimiento, fecha_inicio, fecha_final, telefono, email, municipio, provincia, nombre_plan, bono);
            javax.swing.JOptionPane.showMessageDialog(this, "Cliente editado correctamente \n", "HECHO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
       }
       catch(SQLException e){
           javax.swing.JOptionPane.showMessageDialog(this, "No se ha podido editar el cliente \n", "ERROR", javax.swing.JOptionPane.INFORMATION_MESSAGE);
       }
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Text1;
    private javax.swing.JLabel Text10;
    private javax.swing.JLabel Text11;
    private javax.swing.JLabel Text2;
    private javax.swing.JLabel Text3;
    private javax.swing.JLabel Text4;
    private javax.swing.JLabel Text5;
    private javax.swing.JLabel Text6;
    private javax.swing.JLabel Text7;
    private javax.swing.JLabel Text8;
    private javax.swing.JLabel Text9;
    private javax.swing.JLabel Title;
    private javax.swing.JTextField apellidos;
    private javax.swing.JPanel body;
    private javax.swing.JTextField bono;
    private javax.swing.JPanel button;
    private javax.swing.JTextField email;
    private javax.swing.JTextField fechaFinal;
    private javax.swing.JTextField fechaInicio;
    private javax.swing.JTextField fechaNacimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField municipio;
    private javax.swing.JTextField name;
    private javax.swing.JTextField plan;
    private javax.swing.JTextField provincia;
    private javax.swing.JTextField telefono;
    // End of variables declaration//GEN-END:variables
}
