
package com.app;

import static com.app.Dashboard.content;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import com.bd.Statements;
import java.awt.BorderLayout;

/**
 * 
 * @author diego
 */
public class UpEntrenamiento extends javax.swing.JPanel {

    
    private String origId;
    private Statements statement;
   
    /**
     * Create a new form
     * @param id
     * @param idBono 
     */
    public UpEntrenamiento(String id, String idBono, String fechaInicio){
        initComponents();
        statement = new Statements(Dashboard.user, Dashboard.pwd);
        origId = id;
        bono.setText(idBono);
        fecha.setText(fechaInicio);
        
        jLabel1.setText("Guardar");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        body = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        button = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Text3 = new javax.swing.JLabel();
        bono = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        Text4 = new javax.swing.JLabel();
        fecha = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(750, 430));
        setPreferredSize(new java.awt.Dimension(750, 430));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(body, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Title.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Title.setText("Actualizar el bono");
        add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, -1, -1));

        button.setBackground(new java.awt.Color(18, 90, 173));
        button.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonMousePressed(evt);
            }
        });
        button.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Actualizar");
        button.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, 30));

        add(button, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 260, 50));

        Text3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text3.setText("Bono *");
        add(Text3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, -1, -1));

        bono.setForeground(new java.awt.Color(102, 102, 102));
        bono.setText("Ingrese el bono");
        bono.setBorder(null);
        bono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bonoMousePressed(evt);
            }
        });
        bono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bonoActionPerformed(evt);
            }
        });
        add(bono, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 260, 30));

        jSeparator4.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator4.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 260, 10));

        Text4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text4.setText("Fecha de inicio *");
        add(Text4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, -1, -1));

        fecha.setForeground(new java.awt.Color(102, 102, 102));
        fecha.setText("Ingrese la fecha de inicio");
        fecha.setBorder(null);
        fecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                fechaMousePressed(evt);
            }
        });
        fecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaActionPerformed(evt);
            }
        });
        add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 260, 30));

        jSeparator5.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator5.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 260, 10));
    }// </editor-fold>//GEN-END:initComponents

    private void buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMouseEntered
        setColor(button);
    }//GEN-LAST:event_buttonMouseEntered

    private void buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMouseExited
        resetColor(button);
    }//GEN-LAST:event_buttonMouseExited

    private void bonoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bonoMousePressed
       if(bono.getText().equals("Ingrese el bono"))
        bono.setText("");
       if(fecha.getText().equals("") || fecha.getText() == null || fecha.getText().equals(" "))
            fecha.setText("Ingrese la fecha de inicio");
    }//GEN-LAST:event_bonoMousePressed

    private void bonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bonoActionPerformed

    /**
     * Actualiza el bono del cliente seleccionado
     * @param evt 
     */
    private void buttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMousePressed
        if(bono.getText().equals("Ingrese el bono") || fecha.getText().equals("Ingrese la fecha de inicio")){
            javax.swing.JOptionPane.showMessageDialog(this, "Debe llenar todos los campos \n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            bono.requestFocus();
        }
        else
        {
            String numberBono = bono.getText();
            String fechaInicio = fecha.getText();

            if(numberBono == null || "".equals(numberBono) || fechaInicio == null || "".equals(fechaInicio)){
                javax.swing.JOptionPane.showMessageDialog(this, "Debe llenar todos los campos \n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                bono.requestFocus();
            }
            else{ 
                 edit(Integer.parseInt(origId), Integer.parseInt(numberBono), fechaInicio);
                    
                bono.setText("");
                fecha.setText("");

                Entrenamiento p1 = new Entrenamiento();
                p1.setSize(750, 430);
                p1.setLocation(0, 0);

                content.removeAll();
                content.add(p1, BorderLayout.CENTER);
                content.revalidate();
                content.repaint();
                
            }
        }
    }//GEN-LAST:event_buttonMousePressed

    private void fechaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fechaMousePressed
        if(fecha.getText().equals("Ingrese la fecha de inicio"))
            fecha.setText("");
        if(bono.getText().equals("") || bono.getText() == null || bono.getText().equals(" "))
            bono.setText("Ingrese el bono");
    }//GEN-LAST:event_fechaMousePressed

    private void fechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaActionPerformed

    private void setColor(JPanel panel){
        panel.setBackground(new Color(21,101,192));
    }
    
    private void resetColor(JPanel panel){
        panel.setBackground(new Color(18,90,173));
    }
    
    /**
     * Edita el valor del atributo bono del cliente con el id introducido como parámetro en la base de datos
     * @param id
     * @param bono
     * @throws SQLException 
     */
    public void edit(int id, int bono, String fechaInicio){
        try{
            statement.updateBono(id, bono, fechaInicio);
            javax.swing.JOptionPane.showMessageDialog(this, "Datos editados correctamente \n", "HECHO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
        catch(SQLException e){
            javax.swing.JOptionPane.showMessageDialog(this, "No se han podido editar los datos \n", "ERROR", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Text3;
    private javax.swing.JLabel Text4;
    private javax.swing.JLabel Title;
    private javax.swing.JPanel body;
    private javax.swing.JTextField bono;
    private javax.swing.JPanel button;
    private javax.swing.JTextField fecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    // End of variables declaration//GEN-END:variables
}
