
package com.app;

import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import com.bd.Statements;

/**
 * 
 * @author diego
 */
public class UpMedidas extends javax.swing.JPanel {

    private int idus;
    private Statements statement;
    
    /**
     * Creates new form
     */
    public UpMedidas(int id) {
        initComponents();
        statement = new Statements(Dashboard.user, Dashboard.pwd);
        idus = id;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        body = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        Text1 = new javax.swing.JLabel();
        Text2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        metabolismo = new javax.swing.JTextField();
        agua = new javax.swing.JTextField();
        button = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Text3 = new javax.swing.JLabel();
        peso = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        Text4 = new javax.swing.JLabel();
        altura = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        Text5 = new javax.swing.JLabel();
        masaMuscular = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        Text6 = new javax.swing.JLabel();
        masaGrasa = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        Text7 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        edadMetabolica = new javax.swing.JTextField();
        Text8 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        pecho = new javax.swing.JTextField();
        Text9 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        cintura = new javax.swing.JTextField();
        Text10 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        cadera = new javax.swing.JTextField();
        Text11 = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        gluteo = new javax.swing.JTextField();
        Text12 = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        muslo = new javax.swing.JTextField();
        Text13 = new javax.swing.JLabel();
        jSeparator14 = new javax.swing.JSeparator();
        tobillo = new javax.swing.JTextField();
        Text14 = new javax.swing.JLabel();
        jSeparator15 = new javax.swing.JSeparator();
        brazo = new javax.swing.JTextField();
        jSeparator16 = new javax.swing.JSeparator();
        Text15 = new javax.swing.JLabel();
        jSeparator17 = new javax.swing.JSeparator();
        Text16 = new javax.swing.JLabel();
        jSeparator18 = new javax.swing.JSeparator();
        wrist = new javax.swing.JTextField();
        jSeparator19 = new javax.swing.JSeparator();
        jSeparator20 = new javax.swing.JSeparator();
        Text17 = new javax.swing.JLabel();
        jSeparator21 = new javax.swing.JSeparator();
        fecha = new javax.swing.JTextField();
        jSeparator22 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(750, 430));
        setPreferredSize(new java.awt.Dimension(750, 430));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(body, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Title.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Title.setText("Medidas");
        add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        Text1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text1.setText("Metabolismo");
        add(Text1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, -1, -1));

        Text2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text2.setText("Agua");
        add(Text2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator1.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 200, 10));

        jSeparator2.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator2.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 200, 10));

        jSeparator3.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 10, 350));

        metabolismo.setForeground(new java.awt.Color(102, 102, 102));
        metabolismo.setText("Ingrese el metabolismo");
        metabolismo.setBorder(null);
        metabolismo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                metabolismoMousePressed(evt);
            }
        });
        metabolismo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                metabolismoActionPerformed(evt);
            }
        });
        add(metabolismo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 200, 30));

        agua.setForeground(new java.awt.Color(102, 102, 102));
        agua.setText("Ingrese el agua");
        agua.setBorder(null);
        agua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                aguaMousePressed(evt);
            }
        });
        agua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aguaActionPerformed(evt);
            }
        });
        add(agua, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 200, 30));

        button.setBackground(new java.awt.Color(18, 90, 173));
        button.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonMousePressed(evt);
            }
        });
        button.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registrar");
        button.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        add(button, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 370, 200, 50));

        Text3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text3.setText("Peso");
        add(Text3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        peso.setForeground(new java.awt.Color(102, 102, 102));
        peso.setText("Ingrese el peso");
        peso.setBorder(null);
        peso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pesoMousePressed(evt);
            }
        });
        peso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesoActionPerformed(evt);
            }
        });
        add(peso, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 200, 30));

        jSeparator4.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator4.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 200, 10));

        Text4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text4.setText("Altura");
        add(Text4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        altura.setForeground(new java.awt.Color(102, 102, 102));
        altura.setText("Ingrese la altura");
        altura.setBorder(null);
        altura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                alturaMousePressed(evt);
            }
        });
        altura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alturaActionPerformed(evt);
            }
        });
        add(altura, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 200, 30));

        jSeparator5.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator5.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 200, 10));

        Text5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text5.setText("Masa muscular");
        add(Text5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 160, -1));

        masaMuscular.setForeground(new java.awt.Color(102, 102, 102));
        masaMuscular.setText("Ingrese la masa muscular");
        masaMuscular.setBorder(null);
        masaMuscular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                masaMuscularMousePressed(evt);
            }
        });
        masaMuscular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masaMuscularActionPerformed(evt);
            }
        });
        add(masaMuscular, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 200, 30));

        jSeparator6.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator6.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 200, 10));

        Text6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text6.setText("Masa grasa");
        add(Text6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        masaGrasa.setForeground(new java.awt.Color(102, 102, 102));
        masaGrasa.setText("Ingrese la masa grasa");
        masaGrasa.setBorder(null);
        masaGrasa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                masaGrasaMousePressed(evt);
            }
        });
        masaGrasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masaGrasaActionPerformed(evt);
            }
        });
        add(masaGrasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 200, 30));

        jSeparator7.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator7.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 200, 10));

        Text7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text7.setText("Edad metabólica");
        add(Text7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, -1, -1));

        jSeparator8.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator8.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 200, 10));

        edadMetabolica.setForeground(new java.awt.Color(102, 102, 102));
        edadMetabolica.setText("Ingrese la edad metabólica");
        edadMetabolica.setBorder(null);
        edadMetabolica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                edadMetabolicaMousePressed(evt);
            }
        });
        edadMetabolica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edadMetabolicaActionPerformed(evt);
            }
        });
        add(edadMetabolica, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 200, 30));

        Text8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text8.setText("Pecho");
        add(Text8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, -1, -1));

        jSeparator9.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator9.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 200, 10));

        pecho.setForeground(new java.awt.Color(102, 102, 102));
        pecho.setText("Ingrese el pecho");
        pecho.setBorder(null);
        pecho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pechoMousePressed(evt);
            }
        });
        pecho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pechoActionPerformed(evt);
            }
        });
        add(pecho, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 200, 30));

        Text9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text9.setText("Cintura");
        add(Text9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, -1, -1));

        jSeparator10.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator10.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 200, 10));

        cintura.setForeground(new java.awt.Color(102, 102, 102));
        cintura.setText("Ingrese la cintura");
        cintura.setBorder(null);
        cintura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cinturaMousePressed(evt);
            }
        });
        cintura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cinturaActionPerformed(evt);
            }
        });
        add(cintura, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 200, 30));

        Text10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text10.setText("Cadera");
        add(Text10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, -1, -1));

        jSeparator11.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator11.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 200, 10));

        cadera.setForeground(new java.awt.Color(102, 102, 102));
        cadera.setText("Ingrese la cadera");
        cadera.setBorder(null);
        cadera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                caderaMousePressed(evt);
            }
        });
        cadera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caderaActionPerformed(evt);
            }
        });
        add(cadera, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 200, 30));

        Text11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text11.setText("Bajo glúteo");
        add(Text11, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, -1, -1));

        jSeparator12.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator12.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 200, 10));

        gluteo.setForeground(new java.awt.Color(102, 102, 102));
        gluteo.setText("Ingrese el bajo glúteo");
        gluteo.setBorder(null);
        gluteo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                gluteoMousePressed(evt);
            }
        });
        gluteo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gluteoActionPerformed(evt);
            }
        });
        add(gluteo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 200, 30));

        Text12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text12.setText("Muslo");
        add(Text12, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, -1, -1));

        jSeparator13.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator13.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, 200, 10));

        muslo.setForeground(new java.awt.Color(102, 102, 102));
        muslo.setText("Ingrese el muslo");
        muslo.setBorder(null);
        muslo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                musloMousePressed(evt);
            }
        });
        muslo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musloActionPerformed(evt);
            }
        });
        add(muslo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 200, 30));

        Text13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text13.setText("Tobillo");
        add(Text13, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 40, -1, -1));

        jSeparator14.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator14.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, 200, 10));

        tobillo.setForeground(new java.awt.Color(102, 102, 102));
        tobillo.setText("Ingrese el tobillo");
        tobillo.setBorder(null);
        tobillo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tobilloMousePressed(evt);
            }
        });
        tobillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tobilloActionPerformed(evt);
            }
        });
        add(tobillo, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, 200, 30));

        Text14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text14.setText("Brazo");
        add(Text14, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, -1, -1));

        jSeparator15.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator15.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, 200, 10));

        brazo.setForeground(new java.awt.Color(102, 102, 102));
        brazo.setText("Ingrese el brazo");
        brazo.setBorder(null);
        brazo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                brazoMousePressed(evt);
            }
        });
        brazo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brazoActionPerformed(evt);
            }
        });
        add(brazo, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, 200, 30));

        jSeparator16.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator16.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, 200, 10));

        Text15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text15.setText("Brazo");
        add(Text15, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, -1, -1));

        jSeparator17.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator17.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, 200, 10));

        Text16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text16.setText("Muñeca");
        add(Text16, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, -1, -1));

        jSeparator18.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator18.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 210, 200, 10));

        wrist.setForeground(new java.awt.Color(102, 102, 102));
        wrist.setText("Ingrese la muñeca");
        wrist.setBorder(null);
        wrist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                wristMousePressed(evt);
            }
        });
        wrist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wristActionPerformed(evt);
            }
        });
        add(wrist, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, 200, 30));

        jSeparator19.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator19.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 210, 200, 10));

        jSeparator20.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator20.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator20.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator20, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, 10, 350));

        Text17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text17.setText("Fecha");
        add(Text17, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 220, -1, -1));

        jSeparator21.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator21.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator21, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, 200, 10));

        fecha.setForeground(new java.awt.Color(102, 102, 102));
        fecha.setText("Ingrese la fecha de la consulta");
        fecha.setBorder(null);
        fecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                fechaMousePressed(evt);
            }
        });
        fecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaActionPerformed(evt);
            }
        });
        add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, 200, 30));

        jSeparator22.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator22.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator22, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, 200, 10));
    }// </editor-fold>//GEN-END:initComponents

    private void metabolismoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_metabolismoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_metabolismoActionPerformed

    private void aguaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aguaMousePressed
       
       if(peso.getText().equals("") || peso.getText() == null || peso.getText().equals(" "))
            peso.setText("Ingrese el peso");
       if(altura.getText().equals("") || altura.getText() == null || altura.getText().equals(" "))
            altura.setText("Ingrese la altura");
       if(masaMuscular.getText().equals("") || masaMuscular.getText() == null || masaMuscular.getText().equals(" "))
            masaMuscular.setText("Ingrese la masa muscular");
       if(masaGrasa.getText().equals("") || masaGrasa.getText() == null || masaGrasa.getText().equals(" "))
           masaGrasa.setText("Ingrese la masa grasa");
       if(agua.getText().equals("Ingrese el agua"))
            agua.setText("");
       if(metabolismo.getText().equals("") || metabolismo.getText() == null || metabolismo.getText().equals(" "))
            metabolismo.setText("Ingrese el metabolismo");
       if(edadMetabolica.getText().equals("") || edadMetabolica.getText() == null || edadMetabolica.getText().equals(" "))
            edadMetabolica.setText("Ingrese la edad metabólica");
       if(pecho.getText().equals("") || pecho.getText() == null || pecho.getText().equals(" "))
            pecho.setText("Ingrese el pecho");
       if(cintura.getText().equals("") || cintura.getText() == null || cintura.getText().equals(" "))
            cintura.setText("Ingrese la cintura");
       if(cadera.getText().equals("") || cadera.getText() == null || cadera.getText().equals(" "))
            cadera.setText("Ingrese la cadera");
       if(gluteo.getText().equals("") || gluteo.getText() == null || gluteo.getText().equals(" "))
            gluteo.setText("Ingrese el bajo glúteo");
       if(muslo.getText().equals("") || muslo.getText() == null || muslo.getText().equals(" "))
            muslo.setText("Ingrese el muslo");
       if(tobillo.getText().equals("") || tobillo.getText() == null || tobillo.getText().equals(" "))
            tobillo.setText("Ingrese el bajo glúteo");
       if(brazo.getText().equals("") || brazo.getText() == null || brazo.getText().equals(" "))
            brazo.setText("Ingrese el brazo");
       if(wrist.getText().equals("") || wrist.getText() == null || wrist.getText().equals(" "))
            wrist.setText("Ingrese la muñeca");
       if(fecha.getText().equals("") || fecha.getText() == null || fecha.getText().equals(" "))
            fecha.setText("Ingrese la fecha de la consulta");
    }//GEN-LAST:event_aguaMousePressed

    private void metabolismoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_metabolismoMousePressed
        if(peso.getText().equals("") || peso.getText() == null || peso.getText().equals(" "))
            peso.setText("Ingrese el peso");
       if(altura.getText().equals("") || altura.getText() == null || altura.getText().equals(" "))
            altura.setText("Ingrese la altura");
       if(masaMuscular.getText().equals("") || masaMuscular.getText() == null || masaMuscular.getText().equals(" "))
            masaMuscular.setText("Ingrese la masa muscular");
       if(masaGrasa.getText().equals("") || masaGrasa.getText() == null || masaGrasa.getText().equals(" "))
           masaGrasa.setText("Ingrese la masa grasa");
       if(agua.getText().equals("") || agua.getText() == null || agua.getText().equals(" "))
            agua.setText("Ingrese el agua");
       if(metabolismo.getText().equals("Ingrese el metabolismo"))
            metabolismo.setText("");
       if(edadMetabolica.getText().equals("") || edadMetabolica.getText() == null || edadMetabolica.getText().equals(" "))
            edadMetabolica.setText("Ingrese la edad metabólica");
       if(pecho.getText().equals("") || pecho.getText() == null || pecho.getText().equals(" "))
            pecho.setText("Ingrese el pecho");
       if(cintura.getText().equals("") || cintura.getText() == null || cintura.getText().equals(" "))
            cintura.setText("Ingrese la cintura");
       if(cadera.getText().equals("") || cadera.getText() == null || cadera.getText().equals(" "))
            cadera.setText("Ingrese la cadera");
       if(gluteo.getText().equals("") || gluteo.getText() == null || gluteo.getText().equals(" "))
            gluteo.setText("Ingrese el bajo glúteo");
       if(muslo.getText().equals("") || muslo.getText() == null || muslo.getText().equals(" "))
            muslo.setText("Ingrese el muslo");
       if(tobillo.getText().equals("") || tobillo.getText() == null || tobillo.getText().equals(" "))
            tobillo.setText("Ingrese el bajo glúteo");
       if(brazo.getText().equals("") || brazo.getText() == null || brazo.getText().equals(" "))
            brazo.setText("Ingrese el brazo");
       if(wrist.getText().equals("") || wrist.getText() == null || wrist.getText().equals(" "))
            wrist.setText("Ingrese la muñeca");
       if(fecha.getText().equals("") || fecha.getText() == null || fecha.getText().equals(" "))
            fecha.setText("Ingrese la fecha de la consulta");
    }//GEN-LAST:event_metabolismoMousePressed

    private void buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMouseEntered
        setColor(button);
    }//GEN-LAST:event_buttonMouseEntered

    private void buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMouseExited
        resetColor(button);
    }//GEN-LAST:event_buttonMouseExited

    private void pesoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pesoMousePressed
       if(peso.getText().equals("Ingrese el peso"))
            peso.setText("");
       if(altura.getText().equals("") || altura.getText() == null || altura.getText().equals(" "))
            altura.setText("Ingrese la altura");
       if(masaMuscular.getText().equals("") || masaMuscular.getText() == null || masaMuscular.getText().equals(" "))
            masaMuscular.setText("Ingrese la masa muscular");
       if(masaGrasa.getText().equals("") || masaGrasa.getText() == null || masaGrasa.getText().equals(" "))
           masaGrasa.setText("Ingrese la masa grasa");
       if(agua.getText().equals("") || agua.getText() == null || agua.getText().equals(" "))
            agua.setText("Ingrese el agua");
       if(metabolismo.getText().equals("") || metabolismo.getText() == null || metabolismo.getText().equals(" "))
            metabolismo.setText("Ingrese el metabolismo");
       if(edadMetabolica.getText().equals("") || edadMetabolica.getText() == null || edadMetabolica.getText().equals(" "))
            edadMetabolica.setText("Ingrese la edad metabólica");
       if(pecho.getText().equals("") || pecho.getText() == null || pecho.getText().equals(" "))
            pecho.setText("Ingrese el pecho");
       if(cintura.getText().equals("") || cintura.getText() == null || cintura.getText().equals(" "))
            cintura.setText("Ingrese la cintura");
       if(cadera.getText().equals("") || cadera.getText() == null || cadera.getText().equals(" "))
            cadera.setText("Ingrese la cadera");
       if(gluteo.getText().equals("") || gluteo.getText() == null || gluteo.getText().equals(" "))
            gluteo.setText("Ingrese el bajo glúteo");
       if(muslo.getText().equals("") || muslo.getText() == null || muslo.getText().equals(" "))
            muslo.setText("Ingrese el muslo");   
       if(tobillo.getText().equals("") || tobillo.getText() == null || tobillo.getText().equals(" "))
            tobillo.setText("Ingrese el bajo glúteo");
       if(brazo.getText().equals("") || brazo.getText() == null || brazo.getText().equals(" "))
            brazo.setText("Ingrese el brazo");
       if(wrist.getText().equals("") || wrist.getText() == null || wrist.getText().equals(" "))
            wrist.setText("Ingrese la muñeca");
       if(fecha.getText().equals("") || fecha.getText() == null || fecha.getText().equals(" "))
            fecha.setText("Ingrese la fecha de la consulta");
    }//GEN-LAST:event_pesoMousePressed

    private void alturaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alturaMousePressed
       if(peso.getText().equals("") || peso.getText() == null || peso.getText().equals(" "))
            peso.setText("Ingrese el peso");
       if(altura.getText().equals("Ingrese la altura"))
            altura.setText("");
       if(masaMuscular.getText().equals("") || masaMuscular.getText() == null || masaMuscular.getText().equals(" "))
            masaMuscular.setText("Ingrese la masa muscular");
       if(masaGrasa.getText().equals("") || masaGrasa.getText() == null || masaGrasa.getText().equals(" "))
           masaGrasa.setText("Ingrese la masa grasa");
       if(agua.getText().equals("") || agua.getText() == null || agua.getText().equals(" "))
            agua.setText("Ingrese el agua");
       if(metabolismo.getText().equals("") || metabolismo.getText() == null || metabolismo.getText().equals(" "))
            metabolismo.setText("Ingrese el metabolismo");
       if(edadMetabolica.getText().equals("") || edadMetabolica.getText() == null || edadMetabolica.getText().equals(" "))
            edadMetabolica.setText("Ingrese la edad metabólica");
       if(pecho.getText().equals("") || pecho.getText() == null || pecho.getText().equals(" "))
            pecho.setText("Ingrese el pecho");
       if(cintura.getText().equals("") || cintura.getText() == null || cintura.getText().equals(" "))
            cintura.setText("Ingrese la cintura");
       if(cadera.getText().equals("") || cadera.getText() == null || cadera.getText().equals(" "))
            cadera.setText("Ingrese la cadera");
       if(gluteo.getText().equals("") || gluteo.getText() == null || gluteo.getText().equals(" "))
            gluteo.setText("Ingrese el bajo glúteo");
       if(muslo.getText().equals("") || muslo.getText() == null || muslo.getText().equals(" "))
            muslo.setText("Ingrese el muslo");
       if(tobillo.getText().equals("") || tobillo.getText() == null || tobillo.getText().equals(" "))
            tobillo.setText("Ingrese el bajo glúteo");
       if(brazo.getText().equals("") || brazo.getText() == null || brazo.getText().equals(" "))
            brazo.setText("Ingrese el brazo");
       if(wrist.getText().equals("") || wrist.getText() == null || wrist.getText().equals(" "))
            wrist.setText("Ingrese la muñeca");
       if(fecha.getText().equals("") || fecha.getText() == null || fecha.getText().equals(" "))
            fecha.setText("Ingrese la fecha de la consulta");
    }//GEN-LAST:event_alturaMousePressed

    private void alturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alturaActionPerformed

    private void masaMuscularMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masaMuscularMousePressed
       if(peso.getText().equals("") || peso.getText() == null || peso.getText().equals(" "))
            peso.setText("Ingrese el peso");
       if(altura.getText().equals("") || altura.getText() == null || altura.getText().equals(" "))
            altura.setText("Ingrese la altura");
       if(masaMuscular.getText().equals("Ingrese la masa muscular"))
            masaMuscular.setText("");
       if(masaGrasa.getText().equals("") || masaGrasa.getText() == null || masaGrasa.getText().equals(" "))
           masaGrasa.setText("Ingrese la masa grasa");
       if(agua.getText().equals("") || agua.getText() == null || agua.getText().equals(" "))
            agua.setText("Ingrese el agua");
       if(metabolismo.getText().equals("") || metabolismo.getText() == null || metabolismo.getText().equals(" "))
            metabolismo.setText("Ingrese el metabolismo");
       if(edadMetabolica.getText().equals("") || edadMetabolica.getText() == null || edadMetabolica.getText().equals(" "))
            edadMetabolica.setText("Ingrese la edad metabólica");
       if(pecho.getText().equals("") || pecho.getText() == null || pecho.getText().equals(" "))
            pecho.setText("Ingrese el pecho");
       if(cintura.getText().equals("") || cintura.getText() == null || cintura.getText().equals(" "))
            cintura.setText("Ingrese la cintura");
       if(cadera.getText().equals("") || cadera.getText() == null || cadera.getText().equals(" "))
            cadera.setText("Ingrese la cadera");
       if(gluteo.getText().equals("") || gluteo.getText() == null || gluteo.getText().equals(" "))
            gluteo.setText("Ingrese el bajo glúteo");
       if(muslo.getText().equals("") || muslo.getText() == null || muslo.getText().equals(" "))
            muslo.setText("Ingrese el muslo");
       if(tobillo.getText().equals("") || tobillo.getText() == null || tobillo.getText().equals(" "))
            tobillo.setText("Ingrese el bajo glúteo");
       if(brazo.getText().equals("") || brazo.getText() == null || brazo.getText().equals(" "))
            brazo.setText("Ingrese el brazo");
       if(wrist.getText().equals("") || wrist.getText() == null || wrist.getText().equals(" "))
            wrist.setText("Ingrese la muñeca");
       if(fecha.getText().equals("") || fecha.getText() == null || fecha.getText().equals(" "))
            fecha.setText("Ingrese la fecha de la consulta");
    }//GEN-LAST:event_masaMuscularMousePressed

    private void masaMuscularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masaMuscularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_masaMuscularActionPerformed

    private void pesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesoActionPerformed

    private void aguaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aguaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aguaActionPerformed
    // REGISTRAR
    private void buttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMousePressed
        if(peso.getText().equals("Ingrese el peso") || altura.getText().equals("Ingrese la altura")
            || masaMuscular.getText().equals("Ingrese la masa muscular") || masaGrasa.getText().equals("Ingrese la masa grasa") || agua.getText().equals("Ingrese el agua")
            || metabolismo.getText().equals("Ingrese el metabolismo") || edadMetabolica.getText().equals("Ingrese la edad metabólica") || pecho.getText().equals("Ingrese el pecho") || cintura.getText().equals("Ingrese la cintura") || cadera.getText().equals("Ingrese la cadera")
            || gluteo.getText().equals("Ingrese el glúteo") || tobillo.getText().equals("ingrese el tobillo") || brazo.getText().equals("Ingrese el brazo") || wrist.getText().equals("Ingrese la muñeca") || fecha.getText().equals("Ingrese la fecha de la consulta")){
            javax.swing.JOptionPane.showMessageDialog(this, "Debe llenar todos los campos \n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            peso.requestFocus();
        }
        else
        {
            String upeso = peso.getText();
            String ualtura = altura.getText();
            String umasaMuscular = masaMuscular.getText();
            String umasaGrasa = masaGrasa.getText();
            String uagua = agua.getText();
            String umetabolismo = metabolismo.getText();
            String uedad = edadMetabolica.getText();
            String upecho = pecho.getText();
            String ucintura = cintura.getText();
            String ucadera = cadera.getText();
            String ugluteo = gluteo.getText();
            String umuslo = muslo.getText();
            String utobillo = tobillo.getText();
            String ubrazo = brazo.getText();
            String uwrist = wrist.getText();
            String ufecha = fecha.getText();

            if(upeso == null || "".equals(upeso) || ualtura == null || "".equals(ualtura) || umasaMuscular == null || "".equals(umasaMuscular) || umasaGrasa == null || "".equals(umasaGrasa) || uagua == null || "".equals(uagua) || umetabolismo == null || "".equals(umetabolismo) || uedad == null || "".equals(uedad) || upecho == null || "".equals(upecho) || ucintura == null || "".equals(ucintura) || ucadera == null || "".equals(ucadera) || ugluteo == null || "".equals(ugluteo)  || umuslo == null || "".equals(umuslo) || utobillo == null || "".equals(utobillo) || ubrazo == null || "".equals(ubrazo) || uwrist == null || "".equals(uwrist) || ufecha == null || "".equals(ufecha)){
                javax.swing.JOptionPane.showMessageDialog(this, "Debe llenar todos los campos \n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                peso.requestFocus();
            }
            else{ 
                
                insert(ufecha, Integer.parseInt(upeso), Integer.parseInt(ualtura), Integer.parseInt(umasaMuscular), Integer.parseInt(umasaGrasa), Integer.parseInt(uagua), Integer.parseInt(umetabolismo), Integer.parseInt(uedad), Integer.parseInt(upecho), Integer.parseInt(ucintura), Integer.parseInt(ucadera), Integer.parseInt(ugluteo), Integer.parseInt(umuslo), Integer.parseInt(utobillo), Integer.parseInt(ubrazo), Integer.parseInt(uwrist));

                peso.setText("");
                altura.setText("");
                masaMuscular.setText("");
                masaGrasa.setText("");
                agua.setText("");
                metabolismo.setText("");
                edadMetabolica.setText("");
                pecho.setText("");
                cintura.setText("");
                cadera.setText("");
                gluteo.setText("");
                muslo.setText("");
                tobillo.setText("");
                brazo.setText("");
                wrist.setText("");
                fecha.setText("");
            }
        }
    }//GEN-LAST:event_buttonMousePressed

    private void masaGrasaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masaGrasaMousePressed
       if(peso.getText().equals("") || peso.getText() == null || peso.getText().equals(" "))
            peso.setText("Ingrese el peso");
       if(altura.getText().equals("") || altura.getText() == null || altura.getText().equals(" "))
            altura.setText("Ingrese la altura");
       if(masaMuscular.getText().equals("") || masaMuscular.getText() == null || masaMuscular.getText().equals(" "))
            masaMuscular.setText("Ingrese la masa muscular");
       if(masaGrasa.getText().equals("Ingrese la masa grasa"))
           masaGrasa.setText("");
       if(agua.getText().equals("") || agua.getText() == null || agua.getText().equals(" "))
            agua.setText("Ingrese el agua");
       if(metabolismo.getText().equals("") || metabolismo.getText() == null || metabolismo.getText().equals(" "))
            metabolismo.setText("Ingrese el metabolismo");
       if(edadMetabolica.getText().equals("") || edadMetabolica.getText() == null || edadMetabolica.getText().equals(" "))
            edadMetabolica.setText("Ingrese la edad metabólica");
       if(pecho.getText().equals("") || pecho.getText() == null || pecho.getText().equals(" "))
            pecho.setText("Ingrese el pecho");
       if(cintura.getText().equals("") || cintura.getText() == null || cintura.getText().equals(" "))
            cintura.setText("Ingrese la cintura");
       if(cadera.getText().equals("") || cadera.getText() == null || cadera.getText().equals(" "))
            cadera.setText("Ingrese la cadera");
       if(gluteo.getText().equals("") || gluteo.getText() == null || gluteo.getText().equals(" "))
            gluteo.setText("Ingrese el bajo glúteo");
       if(muslo.getText().equals("") || muslo.getText() == null || muslo.getText().equals(" "))
            muslo.setText("Ingrese el muslo");
       if(tobillo.getText().equals("") || tobillo.getText() == null || tobillo.getText().equals(" "))
            tobillo.setText("Ingrese el bajo glúteo");
       if(brazo.getText().equals("") || brazo.getText() == null || brazo.getText().equals(" "))
            brazo.setText("Ingrese el brazo");
       if(wrist.getText().equals("") || wrist.getText() == null || wrist.getText().equals(" "))
            wrist.setText("Ingrese la muñeca");
       if(fecha.getText().equals("") || fecha.getText() == null || fecha.getText().equals(" "))
            fecha.setText("Ingrese la fecha de la consulta");
    }//GEN-LAST:event_masaGrasaMousePressed

    private void masaGrasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masaGrasaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_masaGrasaActionPerformed

    private void edadMetabolicaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edadMetabolicaMousePressed
        if(peso.getText().equals("") || peso.getText() == null || peso.getText().equals(" "))
            peso.setText("Ingrese el peso");
       if(altura.getText().equals("") || altura.getText() == null || altura.getText().equals(" "))
            altura.setText("Ingrese la altura");
       if(masaMuscular.getText().equals("") || masaMuscular.getText() == null || masaMuscular.getText().equals(" "))
            masaMuscular.setText("Ingrese la masa muscular");
       if(masaGrasa.getText().equals("") || masaGrasa.getText() == null || masaGrasa.getText().equals(" "))
           masaGrasa.setText("Ingrese la masa grasa");
       if(agua.getText().equals("") || agua.getText() == null || agua.getText().equals(" "))
            agua.setText("Ingrese el agua");
       if(metabolismo.getText().equals("") || metabolismo.getText() == null || metabolismo.getText().equals(" "))
            metabolismo.setText("Ingrese el metabolismo");
       if(edadMetabolica.getText().equals("Ingrese la edad metabólica"))
            edadMetabolica.setText("");
       if(pecho.getText().equals("") || pecho.getText() == null || pecho.getText().equals(" "))
            pecho.setText("Ingrese el pecho");
       if(cintura.getText().equals("") || cintura.getText() == null || cintura.getText().equals(" "))
            cintura.setText("Ingrese la cintura");
       if(cadera.getText().equals("") || cadera.getText() == null || cadera.getText().equals(" "))
            cadera.setText("Ingrese la cadera");
       if(gluteo.getText().equals("") || gluteo.getText() == null || gluteo.getText().equals(" "))
            gluteo.setText("Ingrese el bajo glúteo");
       if(muslo.getText().equals("") || muslo.getText() == null || muslo.getText().equals(" "))
            muslo.setText("Ingrese el muslo");
       if(tobillo.getText().equals("") || tobillo.getText() == null || tobillo.getText().equals(" "))
            tobillo.setText("Ingrese el bajo glúteo");
       if(brazo.getText().equals("") || brazo.getText() == null || brazo.getText().equals(" "))
            brazo.setText("Ingrese el brazo");
       if(wrist.getText().equals("") || wrist.getText() == null || wrist.getText().equals(" "))
            wrist.setText("Ingrese la muñeca");
       if(fecha.getText().equals("") || fecha.getText() == null || fecha.getText().equals(" "))
            fecha.setText("Ingrese la fecha de la consulta");
    }//GEN-LAST:event_edadMetabolicaMousePressed

    private void edadMetabolicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edadMetabolicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edadMetabolicaActionPerformed

    private void pechoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pechoMousePressed
       if(peso.getText().equals("") || peso.getText() == null || peso.getText().equals(" "))
            peso.setText("Ingrese el peso");
       if(altura.getText().equals("") || altura.getText() == null || altura.getText().equals(" "))
            altura.setText("Ingrese la altura");
       if(masaMuscular.getText().equals("") || masaMuscular.getText() == null || masaMuscular.getText().equals(" "))
            masaMuscular.setText("Ingrese la masa muscular");
       if(masaGrasa.getText().equals("") || masaGrasa.getText() == null || masaGrasa.getText().equals(" "))
           masaGrasa.setText("Ingrese la masa grasa");
       if(agua.getText().equals("") || agua.getText() == null || agua.getText().equals(" "))
            agua.setText("Ingrese el agua");
       if(metabolismo.getText().equals("") || metabolismo.getText() == null || metabolismo.getText().equals(" "))
            metabolismo.setText("Ingrese el metabolismo");
       if(edadMetabolica.getText().equals("") || edadMetabolica.getText() == null || edadMetabolica.getText().equals(" "))
            edadMetabolica.setText("Ingrese la edad metabólica");
       if(pecho.getText().equals("Ingrese el pecho"))
            pecho.setText("");
       if(cintura.getText().equals("") || cintura.getText() == null || cintura.getText().equals(" "))
            cintura.setText("Ingrese la cintura");
       if(cadera.getText().equals("") || cadera.getText() == null || cadera.getText().equals(" "))
            cadera.setText("Ingrese la cadera");
       if(gluteo.getText().equals("") || gluteo.getText() == null || gluteo.getText().equals(" "))
            gluteo.setText("Ingrese el bajo glúteo");
       if(muslo.getText().equals("") || muslo.getText() == null || muslo.getText().equals(" "))
            muslo.setText("Ingrese el muslo");
       if(tobillo.getText().equals("") || tobillo.getText() == null || tobillo.getText().equals(" "))
            tobillo.setText("Ingrese el bajo glúteo");
       if(brazo.getText().equals("") || brazo.getText() == null || brazo.getText().equals(" "))
            brazo.setText("Ingrese el brazo");
       if(wrist.getText().equals("") || wrist.getText() == null || wrist.getText().equals(" "))
            wrist.setText("Ingrese la muñeca");
       if(fecha.getText().equals("") || fecha.getText() == null || fecha.getText().equals(" "))
            fecha.setText("Ingrese la fecha de la consulta");
    }//GEN-LAST:event_pechoMousePressed

    private void pechoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pechoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pechoActionPerformed

    private void cinturaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cinturaMousePressed
        if(peso.getText().equals("") || peso.getText() == null || peso.getText().equals(" "))
            peso.setText("Ingrese el peso");
       if(altura.getText().equals("") || altura.getText() == null || altura.getText().equals(" "))
            altura.setText("Ingrese la altura");
       if(masaMuscular.getText().equals("") || masaMuscular.getText() == null || masaMuscular.getText().equals(" "))
            masaMuscular.setText("Ingrese la masa muscular");
       if(masaGrasa.getText().equals("") || masaGrasa.getText() == null || masaGrasa.getText().equals(" "))
           masaGrasa.setText("Ingrese la masa grasa");
       if(agua.getText().equals("") || agua.getText() == null || agua.getText().equals(" "))
            agua.setText("Ingrese el agua");
       if(metabolismo.getText().equals("") || metabolismo.getText() == null || metabolismo.getText().equals(" "))
            metabolismo.setText("Ingrese el metabolismo");
       if(edadMetabolica.getText().equals("") || edadMetabolica.getText() == null || edadMetabolica.getText().equals(" "))
            edadMetabolica.setText("Ingrese la edad metabólica");
        if(pecho.getText().equals("") || pecho.getText() == null || pecho.getText().equals(" "))
            pecho.setText("Ingrese el pecho");
       if(cintura.getText().equals("Ingrese la cintura"))
            cintura.setText("");
       if(cadera.getText().equals("") || cadera.getText() == null || cadera.getText().equals(" "))
            cadera.setText("Ingrese la cadera");
       if(gluteo.getText().equals("") || gluteo.getText() == null || gluteo.getText().equals(" "))
            gluteo.setText("Ingrese el bajo glúteo");
       if(muslo.getText().equals("") || muslo.getText() == null || muslo.getText().equals(" "))
            muslo.setText("Ingrese el muslo");
       if(tobillo.getText().equals("") || tobillo.getText() == null || tobillo.getText().equals(" "))
            tobillo.setText("Ingrese el bajo glúteo");
       if(brazo.getText().equals("") || brazo.getText() == null || brazo.getText().equals(" "))
            brazo.setText("Ingrese el brazo");
       if(wrist.getText().equals("") || wrist.getText() == null || wrist.getText().equals(" "))
            wrist.setText("Ingrese la muñeca");
       if(fecha.getText().equals("") || fecha.getText() == null || fecha.getText().equals(" "))
            fecha.setText("Ingrese la fecha de la consulta");
    }//GEN-LAST:event_cinturaMousePressed

    private void cinturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cinturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cinturaActionPerformed

    private void caderaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_caderaMousePressed
        if(peso.getText().equals("") || peso.getText() == null || peso.getText().equals(" "))
            peso.setText("Ingrese el peso");
       if(altura.getText().equals("") || altura.getText() == null || altura.getText().equals(" "))
            altura.setText("Ingrese la altura");
       if(masaMuscular.getText().equals("") || masaMuscular.getText() == null || masaMuscular.getText().equals(" "))
            masaMuscular.setText("Ingrese la masa muscular");
       if(masaGrasa.getText().equals("") || masaGrasa.getText() == null || masaGrasa.getText().equals(" "))
           masaGrasa.setText("Ingrese la masa grasa");
       if(agua.getText().equals("") || agua.getText() == null || agua.getText().equals(" "))
            agua.setText("Ingrese el agua");
       if(metabolismo.getText().equals("") || metabolismo.getText() == null || metabolismo.getText().equals(" "))
            metabolismo.setText("Ingrese el metabolismo");
       if(edadMetabolica.getText().equals("") || edadMetabolica.getText() == null || edadMetabolica.getText().equals(" "))
            edadMetabolica.setText("Ingrese la edad metabólica");
        if(pecho.getText().equals("") || pecho.getText() == null || pecho.getText().equals(" "))
            pecho.setText("Ingrese el pecho");
       if(cintura.getText().equals("") || cintura.getText() == null || cintura.getText().equals(" "))
            cintura.setText("Ingrese la cintura");
       if(cadera.getText().equals("Ingrese la cadera"))
           cadera.setText("");
       if(gluteo.getText().equals("") || gluteo.getText() == null || gluteo.getText().equals(" "))
            gluteo.setText("Ingrese el bajo glúteo");
       if(muslo.getText().equals("") || muslo.getText() == null || muslo.getText().equals(" "))
            muslo.setText("Ingrese el muslo");
       if(tobillo.getText().equals("") || tobillo.getText() == null || tobillo.getText().equals(" "))
            tobillo.setText("Ingrese el bajo glúteo");
       if(brazo.getText().equals("") || brazo.getText() == null || brazo.getText().equals(" "))
            brazo.setText("Ingrese el brazo");
       if(wrist.getText().equals("") || wrist.getText() == null || wrist.getText().equals(" "))
            wrist.setText("Ingrese la muñeca");
       if(fecha.getText().equals("") || fecha.getText() == null || fecha.getText().equals(" "))
            fecha.setText("Ingrese la fecha de la consulta");
    }//GEN-LAST:event_caderaMousePressed

    private void caderaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caderaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caderaActionPerformed

    private void gluteoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gluteoMousePressed
        if(peso.getText().equals("") || peso.getText() == null || peso.getText().equals(" "))
            peso.setText("Ingrese el peso");
       if(altura.getText().equals("") || altura.getText() == null || altura.getText().equals(" "))
            altura.setText("Ingrese la altura");
       if(masaMuscular.getText().equals("") || masaMuscular.getText() == null || masaMuscular.getText().equals(" "))
            masaMuscular.setText("Ingrese la masa muscular");
       if(masaGrasa.getText().equals("") || masaGrasa.getText() == null || masaGrasa.getText().equals(" "))
           masaGrasa.setText("Ingrese la masa grasa");
       if(agua.getText().equals("") || agua.getText() == null || agua.getText().equals(" "))
            agua.setText("Ingrese el agua");
       if(metabolismo.getText().equals("") || metabolismo.getText() == null || metabolismo.getText().equals(" "))
            metabolismo.setText("Ingrese el metabolismo");
       if(edadMetabolica.getText().equals("") || edadMetabolica.getText() == null || edadMetabolica.getText().equals(" "))
            edadMetabolica.setText("Ingrese la edad metabólica");
        if(pecho.getText().equals("") || pecho.getText() == null || pecho.getText().equals(" "))
            pecho.setText("Ingrese el pecho");
       if(cintura.getText().equals("") || cintura.getText() == null || cintura.getText().equals(" "))
            cintura.setText("Ingrese la cintura");
       if(cadera.getText().equals("") || cadera.getText() == null || cadera.getText().equals(" "))
            cadera.setText("Ingrese la cadera");
       if(gluteo.getText().equals("Ingrese el bajo glúteo"))
           gluteo.setText("");
       if(muslo.getText().equals("") || muslo.getText() == null || muslo.getText().equals(" "))
            muslo.setText("Ingrese el muslo");
       if(tobillo.getText().equals("") || tobillo.getText() == null || tobillo.getText().equals(" "))
            tobillo.setText("Ingrese el bajo glúteo");
       if(brazo.getText().equals("") || brazo.getText() == null || brazo.getText().equals(" "))
            brazo.setText("Ingrese el brazo");
       if(wrist.getText().equals("") || wrist.getText() == null || wrist.getText().equals(" "))
            wrist.setText("Ingrese la muñeca");
       if(fecha.getText().equals("") || fecha.getText() == null || fecha.getText().equals(" "))
            fecha.setText("Ingrese la fecha de la consulta");
    }//GEN-LAST:event_gluteoMousePressed

    private void gluteoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gluteoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gluteoActionPerformed

    private void musloMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_musloMousePressed
        if(peso.getText().equals("") || peso.getText() == null || peso.getText().equals(" "))
            peso.setText("Ingrese el peso");
       if(altura.getText().equals("") || altura.getText() == null || altura.getText().equals(" "))
            altura.setText("Ingrese la altura");
       if(masaMuscular.getText().equals("") || masaMuscular.getText() == null || masaMuscular.getText().equals(" "))
            masaMuscular.setText("Ingrese la masa muscular");
       if(masaGrasa.getText().equals("") || masaGrasa.getText() == null || masaGrasa.getText().equals(" "))
           masaGrasa.setText("Ingrese la masa grasa");
       if(agua.getText().equals("") || agua.getText() == null || agua.getText().equals(" "))
            agua.setText("Ingrese el agua");
       if(metabolismo.getText().equals("") || metabolismo.getText() == null || metabolismo.getText().equals(" "))
            metabolismo.setText("Ingrese el metabolismo");
       if(edadMetabolica.getText().equals("") || edadMetabolica.getText() == null || edadMetabolica.getText().equals(" "))
            edadMetabolica.setText("Ingrese la edad metabólica");
        if(pecho.getText().equals("") || pecho.getText() == null || pecho.getText().equals(" "))
            pecho.setText("Ingrese el pecho");
       if(cintura.getText().equals("") || cintura.getText() == null || cintura.getText().equals(" "))
            cintura.setText("Ingrese la cintura");
       if(cadera.getText().equals("") || cadera.getText() == null || cadera.getText().equals(" "))
            cadera.setText("Ingrese la cadera");
       if(gluteo.getText().equals("") || gluteo.getText() == null || gluteo.getText().equals(" "))
            gluteo.setText("Ingrese el bajo glúteo");
       if(muslo.getText().equals("Ingrese el muslo"))
           muslo.setText("");
       if(tobillo.getText().equals("") || tobillo.getText() == null || tobillo.getText().equals(" "))
            tobillo.setText("Ingrese el bajo glúteo");
       if(brazo.getText().equals("") || brazo.getText() == null || brazo.getText().equals(" "))
            brazo.setText("Ingrese el brazo");
       if(wrist.getText().equals("") || wrist.getText() == null || wrist.getText().equals(" "))
            wrist.setText("Ingrese la muñeca");
       if(fecha.getText().equals("") || fecha.getText() == null || fecha.getText().equals(" "))
            fecha.setText("Ingrese la fecha de la consulta");
    }//GEN-LAST:event_musloMousePressed

    private void musloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_musloActionPerformed

    private void tobilloMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tobilloMousePressed
         if(peso.getText().equals("") || peso.getText() == null || peso.getText().equals(" "))
            peso.setText("Ingrese el peso");
       if(altura.getText().equals("") || altura.getText() == null || altura.getText().equals(" "))
            altura.setText("Ingrese la altura");
       if(masaMuscular.getText().equals("") || masaMuscular.getText() == null || masaMuscular.getText().equals(" "))
            masaMuscular.setText("Ingrese la masa muscular");
       if(masaGrasa.getText().equals("") || masaGrasa.getText() == null || masaGrasa.getText().equals(" "))
           masaGrasa.setText("Ingrese la masa grasa");
       if(agua.getText().equals("") || agua.getText() == null || agua.getText().equals(" "))
            agua.setText("Ingrese el agua");
       if(metabolismo.getText().equals("") || metabolismo.getText() == null || metabolismo.getText().equals(" "))
            metabolismo.setText("Ingrese el metabolismo");
       if(edadMetabolica.getText().equals("") || edadMetabolica.getText() == null || edadMetabolica.getText().equals(" "))
            edadMetabolica.setText("Ingrese la edad metabólica");
        if(pecho.getText().equals("") || pecho.getText() == null || pecho.getText().equals(" "))
            pecho.setText("Ingrese el pecho");
       if(cintura.getText().equals("") || cintura.getText() == null || cintura.getText().equals(" "))
            cintura.setText("Ingrese la cintura");
       if(cadera.getText().equals("") || cadera.getText() == null || cadera.getText().equals(" "))
            cadera.setText("Ingrese la cadera");
       if(gluteo.getText().equals("") || gluteo.getText() == null || gluteo.getText().equals(" "))
            gluteo.setText("Ingrese el bajo glúteo");
       if(muslo.getText().equals("") || muslo.getText() == null || muslo.getText().equals(" "))
            muslo.setText("Ingrese el muslo");
       if(tobillo.getText().equals("Ingrese el tobillo"))
           tobillo.setText("");
       if(brazo.getText().equals("") || brazo.getText() == null || brazo.getText().equals(" "))
            brazo.setText("Ingrese el brazo");
       if(wrist.getText().equals("") || wrist.getText() == null || wrist.getText().equals(" "))
            wrist.setText("Ingrese la muñeca");
       if(fecha.getText().equals("") || fecha.getText() == null || fecha.getText().equals(" "))
            fecha.setText("Ingrese la fecha de la consulta");
    }//GEN-LAST:event_tobilloMousePressed

    private void tobilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tobilloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tobilloActionPerformed

    private void brazoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brazoMousePressed
         if(peso.getText().equals("") || peso.getText() == null || peso.getText().equals(" "))
            peso.setText("Ingrese el peso");
       if(altura.getText().equals("") || altura.getText() == null || altura.getText().equals(" "))
            altura.setText("Ingrese la altura");
       if(masaMuscular.getText().equals("") || masaMuscular.getText() == null || masaMuscular.getText().equals(" "))
            masaMuscular.setText("Ingrese la masa muscular");
       if(masaGrasa.getText().equals("") || masaGrasa.getText() == null || masaGrasa.getText().equals(" "))
           masaGrasa.setText("Ingrese la masa grasa");
       if(agua.getText().equals("") || agua.getText() == null || agua.getText().equals(" "))
            agua.setText("Ingrese el agua");
       if(metabolismo.getText().equals("") || metabolismo.getText() == null || metabolismo.getText().equals(" "))
            metabolismo.setText("Ingrese el metabolismo");
       if(edadMetabolica.getText().equals("") || edadMetabolica.getText() == null || edadMetabolica.getText().equals(" "))
            edadMetabolica.setText("Ingrese la edad metabólica");
        if(pecho.getText().equals("") || pecho.getText() == null || pecho.getText().equals(" "))
            pecho.setText("Ingrese el pecho");
       if(cintura.getText().equals("") || cintura.getText() == null || cintura.getText().equals(" "))
            cintura.setText("Ingrese la cintura");
       if(cadera.getText().equals("") || cadera.getText() == null || cadera.getText().equals(" "))
            cadera.setText("Ingrese la cadera");
       if(gluteo.getText().equals("") || gluteo.getText() == null || gluteo.getText().equals(" "))
            gluteo.setText("Ingrese el bajo glúteo");
       if(muslo.getText().equals("") || muslo.getText() == null || muslo.getText().equals(" "))
            muslo.setText("Ingrese el muslo");
       if(tobillo.getText().equals("") || tobillo.getText() == null || tobillo.getText().equals(" "))
            tobillo.setText("Ingrese el bajo glúteo");
        if(brazo.getText().equals("Ingrese el brazo"))
           brazo.setText("");
        if(wrist.getText().equals("") || wrist.getText() == null || wrist.getText().equals(" "))
            wrist.setText("Ingrese la muñeca");
        if(fecha.getText().equals("") || fecha.getText() == null || fecha.getText().equals(" "))
            fecha.setText("Ingrese la fecha de la consulta");
    }//GEN-LAST:event_brazoMousePressed

    private void brazoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brazoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brazoActionPerformed

    private void wristMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wristMousePressed
        if(peso.getText().equals("") || peso.getText() == null || peso.getText().equals(" "))
            peso.setText("Ingrese el peso");
       if(altura.getText().equals("") || altura.getText() == null || altura.getText().equals(" "))
            altura.setText("Ingrese la altura");
       if(masaMuscular.getText().equals("") || masaMuscular.getText() == null || masaMuscular.getText().equals(" "))
            masaMuscular.setText("Ingrese la masa muscular");
       if(masaGrasa.getText().equals("") || masaGrasa.getText() == null || masaGrasa.getText().equals(" "))
           masaGrasa.setText("Ingrese la masa grasa");
       if(agua.getText().equals("") || agua.getText() == null || agua.getText().equals(" "))
            agua.setText("Ingrese el agua");
       if(metabolismo.getText().equals("") || metabolismo.getText() == null || metabolismo.getText().equals(" "))
            metabolismo.setText("Ingrese el metabolismo");
       if(edadMetabolica.getText().equals("") || edadMetabolica.getText() == null || edadMetabolica.getText().equals(" "))
            edadMetabolica.setText("Ingrese la edad metabólica");
        if(pecho.getText().equals("") || pecho.getText() == null || pecho.getText().equals(" "))
            pecho.setText("Ingrese el pecho");
       if(cintura.getText().equals("") || cintura.getText() == null || cintura.getText().equals(" "))
            cintura.setText("Ingrese la cintura");
       if(cadera.getText().equals("") || cadera.getText() == null || cadera.getText().equals(" "))
            cadera.setText("Ingrese la cadera");
       if(gluteo.getText().equals("") || gluteo.getText() == null || gluteo.getText().equals(" "))
            gluteo.setText("Ingrese el bajo glúteo");
       if(muslo.getText().equals("") || muslo.getText() == null || muslo.getText().equals(" "))
            muslo.setText("Ingrese el muslo");
       if(tobillo.getText().equals("") || tobillo.getText() == null || tobillo.getText().equals(" "))
            tobillo.setText("Ingrese el bajo glúteo");
        if(brazo.getText().equals("") || brazo.getText() == null || brazo.getText().equals(" "))
            brazo.setText("Ingrese el brazo");
        if(wrist.getText().equals("Ingrese la muñeca"))
           wrist.setText("");
        if(fecha.getText().equals("") || fecha.getText() == null || fecha.getText().equals(" "))
            fecha.setText("Ingrese la fecha de la consulta");
    }//GEN-LAST:event_wristMousePressed

    private void wristActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wristActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wristActionPerformed

    private void fechaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fechaMousePressed
        if(peso.getText().equals("") || peso.getText() == null || peso.getText().equals(" "))
            peso.setText("Ingrese el peso");
       if(altura.getText().equals("") || altura.getText() == null || altura.getText().equals(" "))
            altura.setText("Ingrese la altura");
       if(masaMuscular.getText().equals("") || masaMuscular.getText() == null || masaMuscular.getText().equals(" "))
            masaMuscular.setText("Ingrese la masa muscular");
       if(masaGrasa.getText().equals("") || masaGrasa.getText() == null || masaGrasa.getText().equals(" "))
           masaGrasa.setText("Ingrese la masa grasa");
       if(agua.getText().equals("") || agua.getText() == null || agua.getText().equals(" "))
            agua.setText("Ingrese el agua");
       if(metabolismo.getText().equals("") || metabolismo.getText() == null || metabolismo.getText().equals(" "))
            metabolismo.setText("Ingrese el metabolismo");
       if(edadMetabolica.getText().equals("") || edadMetabolica.getText() == null || edadMetabolica.getText().equals(" "))
            edadMetabolica.setText("Ingrese la edad metabólica");
        if(pecho.getText().equals("") || pecho.getText() == null || pecho.getText().equals(" "))
            pecho.setText("Ingrese el pecho");
       if(cintura.getText().equals("") || cintura.getText() == null || cintura.getText().equals(" "))
            cintura.setText("Ingrese la cintura");
       if(cadera.getText().equals("") || cadera.getText() == null || cadera.getText().equals(" "))
            cadera.setText("Ingrese la cadera");
       if(gluteo.getText().equals("") || gluteo.getText() == null || gluteo.getText().equals(" "))
            gluteo.setText("Ingrese el bajo glúteo");
       if(muslo.getText().equals("") || muslo.getText() == null || muslo.getText().equals(" "))
            muslo.setText("Ingrese el muslo");
       if(tobillo.getText().equals("") || tobillo.getText() == null || tobillo.getText().equals(" "))
            tobillo.setText("Ingrese el bajo glúteo");
        if(brazo.getText().equals("") || brazo.getText() == null || brazo.getText().equals(" "))
            brazo.setText("Ingrese el brazo");
        if(wrist.getText().equals("") || wrist.getText() == null || wrist.getText().equals(" "))
            wrist.setText("Ingrese la muñeca");
        if(fecha.getText().equals("Ingrese la fecha de la consulta"))
           fecha.setText("");
    }//GEN-LAST:event_fechaMousePressed

    private void fechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaActionPerformed

    private void setColor(JPanel panel){
        panel.setBackground(new Color(21,101,192));
    }
    
    private void resetColor(JPanel panel){
        panel.setBackground(new Color(18,90,173));
    }
    
    public void insert(String fecha, int peso, int altura, int masaMuscular, int masaGrasa, int agua, int metabolismo, int edad, int pecho, int cintura, int cadera, int gluteo, int muslo, int tobillo, int brazo, int wrist) {
        try{
            statement.insertMedidas(idus, fecha, peso, altura, cadera, cintura, muslo, brazo, wrist, tobillo, gluteo, pecho);
            statement.insertBioimpedancias(idus, fecha, masaMuscular, masaGrasa, agua, metabolismo, edad);
            javax.swing.JOptionPane.showMessageDialog(this, "Medidas añadidas correctamente \n", "HECHO", javax.swing.JOptionPane.INFORMATION_MESSAGE); 
        }
        catch(SQLException e){
            javax.swing.JOptionPane.showMessageDialog(this, "No se han añadido las medidas \n", "ERROR", javax.swing.JOptionPane.INFORMATION_MESSAGE); 
        }
       
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Text1;
    private javax.swing.JLabel Text10;
    private javax.swing.JLabel Text11;
    private javax.swing.JLabel Text12;
    private javax.swing.JLabel Text13;
    private javax.swing.JLabel Text14;
    private javax.swing.JLabel Text15;
    private javax.swing.JLabel Text16;
    private javax.swing.JLabel Text17;
    private javax.swing.JLabel Text2;
    private javax.swing.JLabel Text3;
    private javax.swing.JLabel Text4;
    private javax.swing.JLabel Text5;
    private javax.swing.JLabel Text6;
    private javax.swing.JLabel Text7;
    private javax.swing.JLabel Text8;
    private javax.swing.JLabel Text9;
    private javax.swing.JLabel Title;
    private javax.swing.JTextField agua;
    private javax.swing.JTextField altura;
    private javax.swing.JPanel body;
    private javax.swing.JTextField brazo;
    private javax.swing.JPanel button;
    private javax.swing.JTextField cadera;
    private javax.swing.JTextField cintura;
    private javax.swing.JTextField edadMetabolica;
    private javax.swing.JTextField fecha;
    private javax.swing.JTextField gluteo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField masaGrasa;
    private javax.swing.JTextField masaMuscular;
    private javax.swing.JTextField metabolismo;
    private javax.swing.JTextField muslo;
    private javax.swing.JTextField pecho;
    private javax.swing.JTextField peso;
    private javax.swing.JTextField tobillo;
    private javax.swing.JTextField wrist;
    // End of variables declaration//GEN-END:variables
}
